### ISSUE TITLE
make-kpkg is deprecated

### ISSUE THREAD

**Issue by luclu7** [Angristan/LinuxKernelBuild#4]
kernel-package is not available on Debian Stretch, so make-kpkg cannot be used. `make deb-pkg` should be used instead.

**Comment by angristan** [comment]
![ah-icone2-210x210](https://user-images.githubusercontent.com/11699655/34999266-a26350ac-fae1-11e7-967a-7d78bf089d6f.png)

**Comment by luclu7** [comment]
¯\_(ツ)_/¯

**Comment by angristan** [comment]
Fixed in https://github.com/Angristan/LinuxKernelBuild/commit/ac8b14129b657f15a756459d016cf66e4116f28a

I now use `make deb-pkg`

The previous command was `make-kpkg --initrd --revision=$(date +%F) kernel_image kernel_headers`. Do you happen to know how I can use these options now?

Thanks

**Comment by angristan** [comment]
Btw make deb-pkg is way slower ;( https://unix.stackexchange.com/questions/238469/difference-between-make-kpkg-and-make-deb-pkg
